HemlockTown_Agatha_PlayerIsChampion_Text::
    .string "AGATHA: Ah, {PLAYER}! Believe\n"
    .string "it or not, I stay here in\l"
    .string "Hemlock Town. I chose to live\l"
    .string "here because the townspeople\l"
    .string "are so in-tune with nature.\l"
    .string "There are even rumors of\l"
    .string "a mythical forest Pokémon\l"
    .string "living in Hemlock Forest!$"

HemlockTown_Agatha_HasntMet_Text::
    .string "Hmmm... your clothes\n"
    .string "identify you as a Pokémon\l"
    .string "trainer, but your shoes are\l"
    .string "hardly worn. My name is\l"
    .string "Agatha, and I am a member of\l"
    .string "the Kanto Elite Four. I can\l"
    .string "tell by the gleam in your eyes\l"
    .string "that you mean business. I look\l"
    .string "forward to seeing you and your\l"
    .string "Pokémon at the Indigo Plateau.$"

HemlockTown_Agatha_HasMet_Text::
    .string "AGATHA: It's you again. Are\n"
    .string "your Pokémon growing stronger?$"

HemlockTown_Agatha_ComeHere::
    .string "You, child.\n"
    .string "Come here.$"
