SaffronCity_RocketMart_1F_SellMons_Text::
    .string "I like that Pokémon you have there,\n"
    .string "{STR_VAR_1}. I'll give you ¥{STR_VAR_2}\l"
    .string "for it.$"

SaffronCity_RocketMart_1F_PlayerSoldMonForMoney::
    .string "{PLAYER} sold {STR_VAR_1}\n"
    .string "for ¥{STR_VAR_2}.$"

SaffronCity_RocketMart_1F_Sold_Text::
    .string "Pleasure doing business with you.\n"
    .string "Come back any time.$"

SaffronCity_RocketMart_1F_DidntSell_Text::
    .string "Doesn't make a difference to me.\n"
    .string "Come back if you want to sell\l"
    .string "some of your extra Pokémon.$"

SaffronCity_RocketMart_1F_AreYouSure::
    .string "Are you sure you want to sell\n"
    .string "{STR_VAR_1} for ¥{STR_VAR_2}?$"

SaffronCity_RocketMart_1F_NotEnoughMonsText::
    .string "Sorry kid, you only have one\n"
    .string "Pokémon in your party. Come back\l"
    .string "with a few more and I'll\l"
    .string "consider buying them.$"
