SaffronCity_RocketMart_1F_SellMons_Text::
    .string "I like that Pokémon you have there,\n"
    .string "{STR_VAR_1}.\p" 
    .string "I'll give you ¥{STR_VAR_2}\n"
    .string "for it.$"

SaffronCity_RocketMart_1F_PlayerSoldMonForMoney::
    .string "{PLAYER} sold {STR_VAR_1}\n"
    .string "for ¥{STR_VAR_2}.$"

SaffronCity_RocketMart_1F_Sold_Text::
    .string "Pleasure doing business with you.\n"
    .string "Come back any time.$"

SaffronCity_RocketMart_1F_DidntSell_Text::
    .string "Doesn't make a difference to me.\n"
    .string "Come back if you want to sell\l"
    .string "some of your extra Pokémon.$"

SaffronCity_RocketMart_1F_AreYouSure::
    .string "Are you sure you want to sell\n"
    .string "{STR_VAR_1} for ¥{STR_VAR_2}?$"

SaffronCity_RocketMart_1F_NotEnoughMonsText::
    .string "Sorry kid, you only have one\n"
    .string "Pokémon in your party. Come back\l"
    .string "with a few more and I'll\l"
    .string "consider buying them.$"

SaffronCity_RocketMart_1F_SecondRocketGrunt_Text::
    .string "After the Boss lost to you in\n"
    .string "Viridian, TEAM ROCKET disbanded.\p"
    .string "But nobody realized how much\n"
    .string "equipment we had left from the\l"
    .string "golden days. We sold it when nobody\l"
    .string "was looking, and now we're rich!\p"
    .string "We're gonna use the Pokémon\n"
    .string "we buy from trainers to\l"
    .string "take over Johto next!$"

SaffronCity_RocketMart_1F_Scientist_Text::
    .string "I was a double agent working\n"
    .string "for TEAM ROCKET at Silph.\p"
    .string "I was actually on the MASTER BALL\n"
    .string "team. I'm trying to recreate it\l"
    .string "so I can capture strong Pokémon\l"
    .string "to help the conquest of Johto.$"

SaffronCity_RocketMart_1F_Clipboard_Text::
    .string "This research paper looks more\n"
    .string "like alchemy than science…\p"
    .string "Something about the move Imprison…$"
