gOtherText_NewName:: @ 81C574F
    .string "NEW NAME$"

gNameChoice_Green:: @ 81C5758
    .string "Green$"

gNameChoice_Red:: @ 81C575E
    .string "Red$"

gNameChoice_Leaf:: @ 81C5762
    .string "LEAF$"

gNameChoice_Fire:: @ 81C5767
    .string "Fire$"

gNameChoice_Gary:: @ 81C576C
    .string "Gary$"

gNameChoice_Kaz:: @ 81C5771
    .string "Charles$"

gNameChoice_Toru:: @ 81C5775
    .string "Alex$"

gNameChoice_Ash:: @ 81C577A
    .string "Ash$"

gNameChoice_Kene:: @ 81C577E
    .string "Alex$"

gNameChoice_Geki:: @ 81C5783
    .string "Charles$"

gNameChoice_Jak:: @ 81C5788
    .string "JAK$"

gNameChoice_Janne:: @ 81C578C
    .string "JANNE$"

gNameChoice_Jonn:: @ 81C5792
    .string "JONN$"

gNameChoice_Kamon:: @ 81C5797
    .string "KAMON$"

gNameChoice_Karl:: @ 81C579D
    .string "KARL$"

gNameChoice_Taylor:: @ 81C57A2
    .string "TAYLOR$"

gNameChoice_Oscar:: @ 81C57A9
    .string "OSCAR$"

gNameChoice_Hiro:: @ 81C57AF
    .string "HIRO$"

gNameChoice_Max:: @ 81C57B4
    .string "MAX$"

gNameChoice_Jon:: @ 81C57B8
    .string "JON$"

gNameChoice_Ralph:: @ 81C57BC
    .string "RALPH$"

gNameChoice_Kay:: @ 81C57C2
    .string "KAY$"

gNameChoice_Tosh:: @ 81C57C6
    .string "TOSH$"

gNameChoice_Roak:: @ 81C57CB
    .string "ROAK$"

gNameChoice_Omi:: @ 81C57D0
    .string "OMI$"

gNameChoice_Jodi:: @ 81C57D4
    .string "JODI$"

gNameChoice_Amanda:: @ 81C57D9
    .string "AMANDA$"

gNameChoice_Hillary:: @ 81C57E0
    .string "HILLARY$"

gNameChoice_Makey:: @ 81C57E8
    .string "MAKEY$"

gNameChoice_Michi:: @ 81C57EE
    .string "MICHI$"

gNameChoice_Paula:: @ 81C57F4
    .string "PAULA$"

gNameChoice_June:: @ 81C57FA
    .string "JUNE$"

gNameChoice_Cassie:: @ 81C57FF
    .string "CASSIE$"

gNameChoice_Rey:: @ 81C5806
    .string "REY$"

gNameChoice_Seda:: @ 81C580A
    .string "SEDA$"

gNameChoice_Kiko:: @ 81C580F
    .string "KIKO$"

gNameChoice_Mina:: @ 81C5814
    .string "MINA$"

gNameChoice_Norie:: @ 81C5819
    .string "NORIE$"

gNameChoice_Sai:: @ 81C581F
    .string "SAI$"

gNameChoice_Momo:: @ 81C5823
    .string "MOMO$"

gNameChoice_Suzi:: @ 81C5828
    .string "SUZI$"

gNewGame_HelpDocs1:: @ 81C582D
    .string "I'm Charles, thanks for playing my hack!\n"
    .string "This is my ideal classic POKéMON game.$"

gNewGame_HelpDocs2:: @ 81C5875
    .string "I've optimized it for a single-\n"
    .string "player experience, and upped\n"
    .string "the difficulty a little.$"

gNewGame_HelpDocs3:: @ 81C58BA
    .string "There's lots of extra stuff, and\n"
    .string "often I come back to add more.$"

gNewGame_HelpDocs4:: @ 81C58F9
    .string "Stick around long enough, and\n"
    .string "you might see Johto finished!$"

gNewGame_HelpDocs5:: @ 81C592B
    .string "Although it's rough around the\n"
    .string "edges, it's been so fun to make.$"

gNewGame_HelpDocs6:: @ 81C594F
    .string "I'm always open to feedback, so\n"
    .string "let me know what you think!$"

gNewGame_HelpDocs7:: @ 81C5981
    .string "I hope you enjoy this hobby\n"
    .string "project as much as I have!\n"
    .string "           - Charles Averill$"

gOakText_AskPlayerGender:: @ 81C59D5
    .string "Which appearance would\n"
    .string "you like to assume?$"

gNewGameAdventureIntro1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gNewGameAdventureIntro2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gNewGameAdventureIntro3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakText_WelcomeToTheWorld:: @ 81C5C78
    .string "Hello, there!\n"
    .string "Glad to meet you!\pWelcome to the world of POKéMON!\pMy name is OAK.\pPeople affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

gOakText_WorldInhabited1:: @ 81C5D06
    .string "This world…$"

gOakText_WorldInhabited2:: @ 81C5D12
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakText_PetsBattlingStudy:: @ 81C5D4B
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\pAs for myself…\pI study POKéMON as a profession.\p$"

gOakText_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakText_AskPlayerName:: @ 81C5DEA
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakText_FinalizePlayerName:: @ 81C5E13
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakText_IntroduceRival:: @ 81C5E2E
    .string "This is my grandson.\pHe's been your rival since you both\n"
    .string "were babies.\p…Erm, what was his name now?$"

gOakText_AskRivalName:: @ 81C5E91
    .string "Your rival's name, what was it now?$"

gOakText_ConfirmRivalName:: @ 81C5EB5
    .string "…Er, was it {RIVAL}?$"

gOakText_RememberRivalName:: @ 81C5EC5
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakText_LegendAboutToUnfold:: @ 81C5EF4
    .string "{PLAYER}!\pYour very own POKéMON legend is\n"
    .string "about to unfold!\pA world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
