HemlockTown_House2_MapScripts::
	.byte 0

HemlockTown_House2_Mom::
    lock
    faceplayer
    msgbox HemlockTown_House2_Mom_Text
    release
    end

HemlockTown_House2_Girl::
    lock
    faceplayer
    msgbox HemlockTown_House2_Girl_Text
    release
    end

HemlockTown_House2_NES::
    msgbox HemlockTown_House2_NES_Text, MSGBOX_SIGN
    end

HemlockTown_House2_TV::
    msgbox HemlockTown_House2_TV_Text, MSGBOX_SIGN
    end
