HemlockTown_House2_Girl_Text::
    .string "Pow! Pow! This town ain't\n"
    .string "big enough fer the two of us!$"

HemlockTown_House2_Mom_Text::
    .string "She's been playing that game for\n"
    .string "days. It can get noisy sometimes\l"
    .string "but now she's so interested in\l"
    .string "the Wild West that I can't\l"
    .string "manage to distract her from it!\p"
    .string "I love seeing her happy though.$"

HemlockTown_House2_NES_Text::
    .string "It's an NES! It has the game\n"
    .string "“Gun.Smoke“ in it. Yeehaw!$"

HemlockTown_House2_TV_Text::
    .string "You see a cowboy traveling up\n"
    .string "the screen, shooting baddies as\l"
    .string "he moves.\l"
    .string "…Oops, time to go!$"
