VioletCity_MapScripts::
	.byte 0

VioletCity_TownSign::
    msgbox VioletCity_TownSign_Text, MSGBOX_SIGN
    release
    end

VioletCity_GymSign::
    msgbox VioletCity_GymSign_Text, MSGBOX_SIGN
    release
    end

VioletCity_SproutDojoSign::
    msgbox VioletCity_SproutDojoSign_Text, MSGBOX_SIGN
    release
    end

VioletCity_EarlsAcademySign::
    msgbox VioletCity_EarlsAcademySign_Text, MSGBOX_SIGN
    release
    end
