VioletCity_TownSign_Text:
	.string "VIOLET CITY\n"
	.string "The City of Nostalgic Scents$"

VioletCity_GymSign_Text:
	.string "VIOLET CITY POKéMON GYM\n"
	.string "LEADER: RENNON\p"
	.string "The Elegant Master of\n"
	.string "/insert archetype/ Pokémon$"

VioletCity_SproutDojoSign_Text:
	.string "SPROUT DOJO\n"
	.string "Experience the Way of Pokémon$"

VioletCity_EarlsAcademySign_Text:
	.string "Earl's Pokémon Academy$"
