SaffronCity_RocketMart_2F_Jesse_Text::
    .string "{COLOR BLUE}Magikarp… Feebas… James, why'd\n"
    .string "you only catch crummy fish\l"
    .string "Pokémon?! The boss will be\l"
    .string "furious when he comes back!$"

SaffronCity_RocketMart_2F_Meowth_Text::
    .string "{COLOR RED}Yeah, what's da deal James?\n"
    .string "Usually when you mess up it's\l"
    .string "only about 70% as bad as dis.$"

SaffronCity_RocketMart_2F_James_Text::
    .string "I thought you said you wanted\n"
    .string "Pokémon that were good\l"
    .string "for reeling…$"

SaffronCity_RocketMart_2F_Reply::
    .string "……………$"
