VermilionCity_Text_Brendan_PreChampion::
    .string "Woah, you seem to have\n"
    .string "some Main Character energy. I'm\l"
    .string "Brendan, come talk to us when\l"
    .string "you do something big!$"

VermilionCity_Text_Brendan_PostChampion::
    .string "BRENDAN: Hey, it's {PLAYER}! Can I\n"
    .string "see your Trainer Card?\l"
    .string "...\l"
    .string "Woah, the Kanto Champion??\l"
    .string "What an opportunity, I have to\l"
    .string "battle you!$"

VermilionCity_Text_Brendan_Defeat::
    .string "BRENDAN: Wow... you're the\n"
    .string "strongest trainer I've ever met!$"

VermilionCity_Text_Brendan_GiveRayquaza::
    .string "BRENDAN: Hey {PLAYER}, I have\n"
    .string "something to give you. This\l"
    .string "Pokémon joined me because\l"
    .string "it respected my strength and\l"
    .string "passion. I think it needs to\l"
    .string "travel with you now.$"

VermilionCity_Text_ReceivedRayquaza::
    .string "{PLAYER} received Rayquaza\n"
    .string "from Brendan!$"

VermilionCity_Text_ExplainRayquaza::
    .string "BRENDAN: Rayquaza is one of the\n"
    .string "Legendary Weather Trio Pokémon. It\l"
    .string "helped May and I save Hoenn!\l"
    .string "I'm sure it will help you too.$"

VermilionCity_Text_Brendan_PostBattle::
    .string "BRENDAN: How's Rayquaza doing?\n"
    .string "I'm sure you've gone on a ton\l"
    .string "of adventures together!$"

VermilionCity_Text_May_PreChampion::
    .string "Hey there, my name's May!\n"
    .string "I get the feeling you don't talk\l"
    .string "much. That's okay, Brendan and I\l"
    .string "can talk enough for the 3 of us!$"

VermilionCity_Text_May_PostChampion::
    .string "Hey there, my name's May!\n"
    .string "You seem... different from\l"
    .string "the other trainers I've met\l"
    .string "in Kanto. More silent. I think\l"
    .string "this battle will be very\l"
    .string "interesting!$"

VermilionCity_Text_May_Defeat::
    .string "MAY: I was right, this WAS an\n"
    .string "interesting battle!$"

VermilionCity_Text_May_PostBattle::
    .string "MAY: Which one of us do you\n"
    .string "think is the Hoenn champion?$"
