VermilionCity_Text_Brendan_PreChampion::
    .string "Woah, you seem to have some Main\n"
    .string "Character energy. I'm Brendan,\l"
    .string "come talk to us when you do\l"
    .string "something big!$"

VermilionCity_Text_Brendan_PostChampion::
    .string "Hey, it's {PLAYER}! Can I see your\n"
    .string "Trainer Card?\l"
    .string "...\l"
    .string "Woah, the Kanto Champion??\l"
    .string "What an opportunity, I have to\l"
    .string "battle you!$"

VermilionCity_Text_Brendan_Defeat::
    .string "Wow... you're the strongest\n"
    .string "trainer I've ever met!$"

VermilionCity_Text_Brendan_GiveRayquaza::
    .string "Hey {PLAYER}, I have\n"
    .string "something to give you. This\l"
    .string "Pokemon joined me because\l"
    .string "it respected my strength and\l"
    .string "passion. I think it needs to\l"
    .string "travel with you now.$"

VermilionCity_Text_ReceivedRayquaza::
    .string "{PLAYER} received Rayquaza\n"
    .string "from Brendan!$"

VermilionCity_Text_ExplainRayquaza::
    .string "Rayquaza is a Legendary\n"
    .string "Weather Trio Pokemon. It\l"
    .string "helped May and I save Hoenn!\l"
    .string "I'm sure it will help you too.$"

VermilionCity_Text_Brendan_PostBattle::
    .string "How's Rayquaza doing? I'm\n"
    .string "sure you've gone on a ton\l"
    .string "of adventures together!$"

VermilionCity_Text_May_PreChampion::
    .string "Hey there, my name's May!\n"
    .string "I get the feeling you don't talk\l"
    .string "much. That's okay, Brendan and I\l"
    .string "can talk enough for the 3 of us!$"

VermilionCity_Text_May_PostChampion::
    .string "Hey there, my name's May!\n"
    .string "You seem... different from\l"
    .string "the other trainers I've met\l"
    .string "in Kanto. More silent. I think\l"
    .string "this battle will be very\l"
    .string "interesting!$"

VermilionCity_Text_May_Defeat::
    .string "I was right, this WAS an\n"
    .string "interesting battle!$"

VermilionCity_Text_May_PostBattle::
    .string "Which one of us do you\n"
    .string "think is the Hoenn champion?$"
