HemlockTown_PokemonCenter_1F_OldMan_Text::
    .string "It's so peaceful and quiet here…\p"
    .string "Hey, kid. Take a hint.$"

HemlockTown_PokemonCenter_1F_LittleGirl_Text::
    .string "Hey Trainer! I find stuff like\n"
    .string "this washed up by the boardwalk.\p"
    .string "You can have these!$"

HemlockTown_PokemonCenter_1F_Text_ReceivedMiracleSeed::
    .string "{PLAYER} received a MIRACLE SEED.$"

HemlockTown_PokemonCenter_1F_Text_ReceivedCharcoal::
    .string "{PLAYER} received the CHARCOAL.$"

HemlockTown_PokemonCenter_1F_Text_ReceivedMysticWater::
    .string "{PLAYER} received the MYSTIC WATER.$"

HemlockTown_PokemonCenter_1F_Text_AlreadyGotItems::
    .string "I know what CHARCOAL is, but\n"
    .string "where do MYSTIC WATER and\l"
    .string "MIRACLE SEED come from?$"
