@ Text for this file was split weirdly, and is instead in FourIsland_PokemonCenter_1F/text.inc
@ Theres also an unused JP version of that text in this file instead

FourIsland_House1_AveryIntro::
    .string "Howdy...$"

FourIsland_House1_AveryDefeat::
    .string "Dang nabbit!$"

FourIsland_House1_AveryPostBattle::
    .string "B)$"

FourIsland_House1_MaxIntro::
    .string "Huzzah!$"

FourIsland_House1_MaxDefeat::
    .string "Tough scene... you hate\n"
    .string "to see it!$"

FourIsland_House1_MaxPostBattle::
    .string "Classic... never gets old!$"

FourIsland_House1_Text_YoureAwfullyHeavy:: @ 81A3802
    .string "There! Boing!\n"
    .string "You're awfully heavy!$"

