@ Text for this file was split weirdly, and is instead in FourIsland_PokemonCenter_1F/text.inc
@ Theres also an unused JP version of that text in this file instead

FourIsland_House1_MatthewIntro::
    .string "Hey there! I'm Matthew,\n"
    .string "the creator of this hack!\l"
    .string "These are my friends Max and\l"
    .string "Avery. We were stuck in\l"
    .string "quarantine while I made this.\l"
    .string "Thanks for playing! I hope\l"
    .string "you'll enjoy fighting my team!$"

FourIsland_House1_MatthewDefeat::
    .string "Woah, you're really\n"
    .string "strong! No wonder you\l"
    .string "got this far!$"

FourIsland_House1_MatthewPostBattle::
    .string "MATTHEW: I added in a bunch of\n"
    .string "custom legendary events. How\l"
    .string "many have you seen yet?\l"
    .string "Also, check out my\l"
    .string "GitHub! - CharlesAverill$"

FourIsland_House1_AveryIntro::
    .string "AVERY: Howdy...$"

FourIsland_House1_AveryDefeat::
    .string "Dang nabbit!$"

FourIsland_House1_AveryPostBattle::
    .string "AVERY: B)$"

FourIsland_House1_MaxIntro::
    .string "MAX: Huzzah!$"

FourIsland_House1_MaxDefeat::
    .string "Tough scene... you hate\n"
    .string "to see it!$"

FourIsland_House1_MaxPostBattle::
    .string "MAX: Classic... never gets old!$"

FourIsland_House1_Text_YoureAwfullyHeavy:: @ 81A3802
    .string "There! Boing!\n"
    .string "You're awfully heavy!$"

