Route16_ChanseyGrove_House_ChanseyMan_MyChanseysLikeHelpingOthers_Text::
    .string "Hey there {PLAYER}! Say, my\n"
    .string "Chanseys like to help out strong\l"
    .string "trainers by going easy on them in\l"
    .string "battle. You know, Chanseys have a\l"
    .string "high experience yield, and they\l"
    .string "help the growth of the HP stat!$"

Route16_ChanseyGrove_House_ChanseyMan_WantToBattle_Text::
    .string "Would you like to battle my team\n"
    .string "of Chanseys? It's a great way to\l"
    .string "level up your Pokémon!$"

Route16_ChanseyGrove_House_ChanseyMan_WantToBattleAgain_Text::
    .string "Would you like to battle again?$"

Route16_ChanseyGrove_House_ChanseyMan_LetsDoIt_Text::
    .string "Great! Let's get to it.$"

Route16_ChanseyGrove_House_ChanseyMan_DefeatText::
    .string "Good show!$"

Route16_ChanseyGrove_House_ChanseyMan_DontBattle_Text::
    .string "What a shame, my Chanseys would\n"
    .string "have loved to help your team out!$"

Route16_ChanseyGrove_House_ChanseyMan_MentionEVTrainers_Text::
    .string "You know, I've heard of other\n"
    .string "people whose teams like to help\l"
    .string "trainers out like this. You\l"
    .string "should seek them out!$"
