FuchsiaCity_House3_Text_WouldYouLikeToForgetMove:: @ 81993B9
    .string "Uh…\n"
    .string "Oh, yes, I'm the MOVE DELETER.\p"
    .string "I can make POKéMON forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove:: @ 8199421
    .string "Which POKéMON should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten:: @ 8199445
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove:: @ 8199465
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten:: @ 8199485
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely:: @ 81994B1
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves:: @ 81994EA
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves:: @ 819951F
    .string "What?\n"
    .string "No EGG should know any moves.$"

FuchsiaCity_House3_Eunice_Text_Thinking::
    .string "Route 15? No, I thought\n"
    .string "I checked there already…$"

FuchsiaCity_House3_Eunice_Text_Busy::
    .string "She seems lost in thought…$"

FuchsiaCity_House3_Eunice_Introduction::
    .string "My name is Eunice. For my entire\n"
    .string "life, I've been tracking some\l"
    .string "roaming Legendary Pokémon.\l"
    .string "And you are?\l"
    .string "{PLAYER}? Glad to meet you. I heard\l"
    .string "rumors that some roaming Pokémon\l"
    .string "were spotted around Kanto. I'm\l"
    .string "much too old to go adventuring like\l"
    .string "I used to with my husband all those\l"
    .string "years ago... Could you take\l"
    .string "my place and search for\l"
    .string "the roaming Pokémon?$"

FuchsiaCity_House3_Entei_Intro::
    .string "I'm hearing rumors of a Pokémon\n"
    .string "named Entei being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsEntei::
    .string "Woah! That's Entei! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Raikou_Intro::
    .string "I'm hearing rumors of a Pokémon\n"
    .string "named Raikou being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsRaikou::
    .string "Woah! That's Raikou! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Suicune_Intro::
    .string "I'm hearing rumors of a Pokémon\n"
    .string "named Suicune being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsSuicune::
    .string "Woah! That's Suicune! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Latios_Intro::
    .string "I'm hearing rumors of a Pokémon\n"
    .string "named Latios being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsLatios::
    .string "Woah! That's Latios! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Latias_Intro::
    .string "I'm hearing rumors of a Pokémon\n"
    .string "named Latias being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsLatias::
    .string "Woah! That's Latias! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_AllDone::
    .string "I think that's all the roaming\n"
    .string "Pokémon! Thank you for helping me!$"

FuchsiaCity_House3_GiveBallText::
    .string "I think this might be of help.$"

FuchsiaCity_House3_CanYouShowItToMe::
    .string "Can you show it to me please?$"

FuchisaCity_House3_Eusine_Text::
    .string "Yo! My name's Eusine, I\n"
    .string "wanna help my grandma find\l"
    .string "her Legendary Pokémon. My\l"
    .string "favorite is Suicune!$"

FuchisaCity_House3_Eusine_PostText::
    .string "Thanks for helping grandma\n"
    .string "find her Legendary Pokémon!\p"
    .string "……………………\p"
    .string "Maybe I can ride your\n"
    .string "Suicune some time?$"

EuniceAgent_SayRoamerLocation::
    .string "Reports are showing that\n"
    .string "{STR_VAR_1} has been seen\l"
    .string "around {STR_VAR_2}.$"

EuniceAgent_MeetText::
    .string "Hey there! We haven't met, but\n"
    .string "I recognize you. I'm a friend\l"
    .string "of Eunice, and I help her track\l"
    .string "down the Roaming Pokémon.\p"
    .string "There's a bunch of us around\n"
    .string "Kanto, and we can give you\l"
    .string "the scoop on where the Roamers are!$"

EuniceAgent_GoSeeEunice_Text::
    .string "Woah, you found the Roamer we\n"
    .string "were looking for!\p"
    .string "Go talk to Eunice!$"
