FuchsiaCity_House3_Text_WouldYouLikeToForgetMove:: @ 81993B9
    .string "Uh…\n"
    .string "Oh, yes, I'm the MOVE DELETER.\p"
    .string "I can make POKéMON forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove:: @ 8199421
    .string "Which POKéMON should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten:: @ 8199445
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove:: @ 8199465
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten:: @ 8199485
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely:: @ 81994B1
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves:: @ 81994EA
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves:: @ 819951F
    .string "What?\n"
    .string "No EGG should know any moves.$"

FuchsiaCity_House3_Eusine_Text_Thinking::
    .string "Route 15? No, I thought I checked\n"
    .string "there already..."

FuchsiaCity_House3_Eusine_Text_Busy::
    .string "He seems to be lost in thought...$"

FuchsiaCity_House3_Eusine_Introduction::
    .string "My name is Eunice. For my entire\n"
    .string "life, I've been tracking some\l"
    .string "roaming Legendary Pokemon.\l"
    .string "And you are?\l"
    .string "{PLAYER}? Glad to meet you. I heard\l"
    .string "rumors that some roaming Pokemon\l"
    .string "were spotted around Kanto.\l"
    .string "I'm much too old to go adventuring\l"
    .string "like I used to with Ethan all those\l"
    .string "years ago... Could you take my place\l"
    .string "and search for the roaming Pokemon?$"

FuchsiaCity_House3_Entei_Intro::
    .string "I'm hearing rumors of a Pokemon\n"
    .string "named ENTEI being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsEntei::
    .string "Woah! That's ENTEI! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Raikou_Intro::
    .string "I'm hearing rumors of a Pokemon\n"
    .string "named RAIKOU being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsRaikou::
    .string "Woah! That's RAIKOU! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Suicune_Intro::
    .string "I'm hearing rumors of a Pokemon\n"
    .string "named SUICUNE being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsSuicune::
    .string "Woah! That's SUICUNE! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Latios_Intro::
    .string "I'm hearing rumors of a Pokemon\n"
    .string "named LATIOS being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsLatios::
    .string "Woah! That's LATIOS! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_Latias_Intro::
    .string "I'm hearing rumors of a Pokemon\n"
    .string "named LATIAS being seen around\l"
    .string "Kanto right now.$"

FuchsiaCity_House3_WoahThatsLatias::
    .string "Woah! That's LATIAS! Thank you\n"
    .string "for showing me!$"

FuchsiaCity_House3_AllDone::
    .string "I think that's all the roaming\n"
    .string "Pokemon! Thank you for helping me!$"

FuchsiaCity_House3_GiveBallText::
    .string "I think this might be of help.$"

FuchsiaCity_House3_CanYouShowItToMe::
    .string "Can you show it to me please?$"

FuchisaCity_House3_Eusine_Text::
    .string "Yo! My name's Eusine, I\n"
    .string "wanna help my grandma find\l"
    .string "her Legendary Pokemon, my\l"
    .string "favorite is Suicune!$"