LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere:: @ 819358E
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo:: @ 81935ED
    .string "That's odd, MR. FUJI isn't here.\n"
    .string "Where'd he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother:: @ 819361D
    .string "MR. FUJI had been praying alone\n"
    .string "for CUBONE's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons:: @ 8193652
    .string "This is really MR. FUJI's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned POKéMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug:: @ 81936B4
    .string "It's so warm!\n"
    .string "POKéMON are so nice to hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino:: @ 81936DE
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck:: @ 81936EE
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis:: @ 81936FF
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your POKéDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for POKéMON,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji:: @ 81937BD
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute:: @ 81937E5
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Try using it on POKéMON that are\n"
    .string "sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis:: @ 819385B
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou:: @ 8193878
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped:: @ 81938A0
    .string "POKéMON FAN MAGAZINE\n"
    .string "Monthly Grand Prize Drawing!\p"
    .string "The application form is…\p"
    .string "Gone! It's been clipped out.\n"
    .string "Someone must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf:: @ 819392B
    .string "POKéMON magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"

LavenderTown_VolunteerPokemonHouse_Text_MentionJirachi::
    .string "MR. FUJI: {PLAYER}! It's been too\n"
    .string "long! Say, I've been meaning to\l"
    .string "talk to you about something.\l"
    .string "The last few times I visited\l"
    .string "Pokémon Tower, I noticed a strange\l"
    .string "presence on the top floor. I'm not\l"
    .string "sure what it could be, but it\l"
    .string "felt most benevolent. Your love\l"
    .string "for Pokémon has taken you this\l"
    .string "far in your journey. Perhaps you\l"
    .string "could visit the Tower and discover\l"
    .string "the source?$"

LavenderTown_VolunteerPokemonHouse_Text_HaveYouVisitedTowerYet::
    .string "Have you been to the Pokémon Tower\n"
    .string "to check out the benevolvent\l"
    .string "presence yet?$"

LavenderTown_VolunteerPokemonHouse_Text_CaughtJirachi::
    .string "Ah, so it was the Wish Pokémon! It\n"
    .string "is known to only show itself to\l"
    .string "the purest of humans. It must have\l"
    .string "had great trust in you to\l"
    .string "reveal itself.$"
