HemlockTown_House3_Text_WantToHear::
    .string "Would you like me to tell\n"
    .string "you about the mythical Pokémon\l"
    .string "that guards our serene forest?$"

HemlockTown_House3_Text_DontWantToHear::
    .string "Bah. You youngsters never\n"
    .string "feel the need to learn from\l"
    .string "the past. It'll be your\l"
    .string "downfall one day.$"

HemlockTown_House3_Text_MentionCelebi::
    .string "Our guardian is the\n"
    .string "celestial being Celebi.$"

HemlockTown_House3_Text_TalkAboutCelebi::
    .string "Celebi is a time-traveling Pokémon\n"
    .string "that is revered in the nearby Johto\l"
    .string "region. While it is said to guard\l"
    .string "Johto's ILEX FOREST, we believe\l"
    .string "that Celebi cares for all life,\l"
    .string "and watches over us forest\l"
    .string "dwellers. Over the years, the\l"
    .string "mythos of Celebi has grown to\l"
    .string "include the idea that as long\l"
    .string "as Celebi appears, a bright,\l"
    .string "shining future awaits us. Is this a\l"
    .string "self-fulfilling prophecy?\l"
    .string "I do not know.\l"
    .string "…\l"
    .string "But it is what I choose to believe.$"