PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou:: @ 818D2F0
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou:: @ 818D360
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest:: @ 818D3D1
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare:: @ 818D3F8
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad:: @ 818D43E
    .string "There's a show on TV.\n"
    .string "Four men are standing in an alley.\p"
    .string "…Yup.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad:: @ 818D492
    .string "There's a show on TV.\n"
    .string "Four elderly women are sharing\n"
    .string "a home together in Miami.\p"
    .string "…I wish I could stay to watch.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide:: @ 818D4F9
    .string "Oops, wrong side…$"

