CharlesLaboratory_Solomon_Not_Done_Text:
    .string "He's lost in thought with\n"
    .string "his eyes closed...$"

CharlesLaboratory_Solomon_Done_Text1:
    .string "Huh? What? Sorry, I was mulling\n"
    .string "over this problem I've been\l"
    .string "having with my heavy-quark\l"
    .string "production collider. You see\l"
    .string "I keep getting interference\l"
    .string "from... $"

CharlesLaboratory_Solomon_Done_Text2:
    .string "Sorry, I'm all over\n"
    .string "the place today. I never introduced\l"
    .string "myself, I'm Prof. Charles,\l"
    .string "at your service. You said you\l"
    .string "met Solomon? And he led you\l"
    .string "to the Rainbow and Diving Pokémon??\l"
    .string "Wow, he must really trust you,\l"
    .string "we swore to only tell a worthy\l"
    .string "soul should we find one.$"

CharlesLaboratory_Solomon_Done_Text3:
    .string "CHARLES: You know, I'm\n"
    .string "actually in a similar\l"
    .string "position, although I'm so bogged\l"
    .string "down with my research that\l"
    .string "I haven't been able to investigate\l"
    .string "my findings. I picked up some\l"
    .string "strange readings from some\l"
    .string "coordinates out in the ocean,\l"
    .string "there are some major Gamma\l"
    .string "ray bursts coming from a strange\l"
    .string "island. If you handled the\l"
    .string "Rainbow and Diving Pokémon,\l"
    .string "I think you're well-suited\l"
    .string "to the task of checking this\l"
    .string "out. $"

CharlesLaboratory_Solomon_Done_Text4:
    .string "CHARLES: Here, take this\n"
    .string "AuroraTicket, it has the\l"
    .string "location of the Gamma ray\l"
    .string "bursts written on it. If\l"
    .string "you take it to a port you\l"
    .string "can find a ferry to\l"
    .string "take you there.$"

CharlesLaboratory_HaventUsedTicket_Text:
    .string "CHARLES: Have you visited\n"
    .string "the island yet?$"

sText_AuroraTicketNoPlace:
	.string "Can you come back when you have\n"
	.string "more space in your bag?$"

CharlesLaboratory_Completed_Text:
    .string "CHARLES: Woah, so it was a\n"
    .string "Pokémon this whole time?\l"
    .string "I've never seen one like that.$\l"

CharlesLaboratory_Charles_Done_Text::
    .string "I can't thank you enough for\n"
    .string "helping me out with this! The\l"
    .string "scientific implications alone\l"
    .string "are tremendous!$"

CharlesLaboratory_ComputerScreen_Text::
    .string "The computer screen is filled\n"
    .string "with equations and code beyond\l"
    .string "comprehension.$"

CharlesLaboratory_Machine_Text::
    .string "A swirling blue fluid pulses\n"
    .string "regularly. A note next to the\l"
    .string "control panel reads:\l"
    .string "WARNING: HIGHLY VOLATILE MATERIAL!$"

CharlesLaboratory_ParticleAccelerator_Text::
    .string "Flashes of light come from the tube\n"
    .string "in the middle every once in a while.\l"
    .string "The readout on the machine shows:\l"
    .string "SINGULARITY GENERATION TRIALS$"
