@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords:: @ 818AB73
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded:: @ 818AB8E
    .string "{PLAYER} entered a password.\p"
    .string "“GOLDEEN need log.”\p"
    .string "… …  … …  … …\p"
    .string "Another password is needed to\n"
    .string "open the door…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened:: @ 818ABF4
    .string "{PLAYER} entered two passwords.\p"
    .string "“GOLDEEN need log.”\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "… …  … …  … …\p"
    .string "The WAREHOUSE's door opened!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen:: @ 818AC62
    .string "The WAREHOUSE's door is already\n"
    .string "open.$"

FiveIsland_Meadow_Text_Rocket1Intro:: @ 818AC88
    .string "This area's strictly off-limits!\n"
    .string "Out, out!$"

FiveIsland_Meadow_Text_Rocket1Defeat:: @ 818ACB3
    .string "Is this for real?$"

FiveIsland_Meadow_Text_Rocket1PostBattle:: @ 818ACC5
    .string "You don't have any business here!\n"
    .string "Go home!$"

FiveIsland_Meadow_Text_Rocket2Intro:: @ 818ACF0
    .string "There's nothing past here except\n"
    .string "our WAREHOUSE.\p"
    .string "So what brings you here?$"

FiveIsland_Meadow_Text_Rocket2Defeat:: @ 818AD39
    .string "That wasn't supposed to happen…$"

FiveIsland_Meadow_Text_Rocket2PostBattle:: @ 818AD59
    .string "You're wanting to know what's inside\n"
    .string "this WAREHOUSE?\p"
    .string "It's better you didn't know.\n"
    .string "For your own sake, I mean.$"

FiveIsland_Meadow_Text_Rocket3Intro:: @ 818ADC6
    .string "You'd be wasting time even if you\n"
    .string "were to get by me.$"

FiveIsland_Meadow_Text_Rocket3Defeat:: @ 818ADFB
    .string "Oh, that makes me furious!$"

FiveIsland_Meadow_Text_Rocket3PostBattle:: @ 818AE16
    .string "You won't be able to get in without\n"
    .string "the passwords anyway.$"

FiveIsland_BothLegendaryBirds_Fought_Text:
    .string "Seems I was right about ye, {PLAYER}.$"

FiveIsland_HoOh_Fought_Text:
	.string "Hm. The wind seems to beckon at ye.\n"
	.string "Find the Legendary Diving Pokémon.$"

FiveIsland_Lugia_Fought_Text:
	.string "Hm. The sun seems to beckon at ye.\n"
	.string "Find the Legendary Rainbow Pokémon.$"

FiveIsland_Neither_Fought_Text:
    .string "Hm. Come back triumphant.$"

sText_MysticTicketNoPlace: @ 84897EE
	.string "Come back when you have space for it.$"

FiveIsland_Meadow_SailorSolomon_Text_0:
	.string "Ahoy, {PLAYER}. I've heard quite a\n"
	.string "bit about ye, though it seems ye\l"
	.string "know very little about me.\l"
	.string "The wind has whispered the\l"
	.string "name of a young person who has\l"
	.string "grown to be quite the\l"
	.string "powerful trainer. Is this you?$"

FiveIsland_Meadow_SailorSolomon_Text_1:
	.string "Amusin'. I knew ye were the one\n"
	.string "when I heard yer footsteps\l"
	.string "approaching this grassy knoll.\l"
	.string "I am called Captain Solomon\l"
	.string "and I am the holder of a\l"
	.string "great secret. I've been waiting\l"
	.string "to find someone strong enough to\l"
	.string "pass the secret to.$"

FiveIsland_Meadow_SailorSolomon_Text_2:
	.string "SOLOMON: On my travels I have\n"
	.string "discovered the locations of\l"
	.string "the ephemeral Rainbow and\l"
	.string "Diving Pokémon. I believe they\l"
	.string "lie in wait of a powerful trainer\l"
	.string "to ally with.\l"
	.string "And I believe that to be ye.$"

FiveIsland_Meadow_SailorSolomon_Text_3:
	.string "SOLOMON: Take this MysticTicket.\n"
	.string "I've listed the coordinates of\l"
	.string "the island where the Legendary\l"
	.string "Pokémon await you. Show it to\l"
	.string "the sailor in the port city of\l"
	.string "Vermilion, and he will take\l"
	.string "you to the island.$"

FiveIsland_Meadow_SailorSolomon_Text_4:
	.string "SOLOMON: {PLAYER}!\n"
	.string "Weigh anchor and travel to\l"
	.string "the Legendary Pokémon!$"

FiveIsland_TalkToCharles_Text:
    .string "SOLOMON: Long ago I parted\n"
    .string "ways with a man named Charles.\l"
    .string "We were good friends. If I\l"
    .string "had to guess, he's workin'\l"
    .string "on somethin' mighty interestin'.\l"
    .string "Should ye visit him in the\l"
    .string "City o' Saffron, ye might\l"
    .string "hear somethin' worthwhile.$"

FiveIsland_NotYet_Text::
    .string "Not yet…$"
