Route2_Text_RouteSign:: @ 818345E
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave:: @ 8183482
    .string "DIGLETT'S CAVE$"

Route2_EventScript_ChanseyGroveMan_PrivateProperty_Text::
    .string "I'm sorry, but this is\n"
    .string "private property. Please leave.$"

Route2_EventScript_ChanseyGroveMan_AhTheChampion_Text::
    .string "Ah, the Kanto Champion! It's\n"
    .string "a pleasure to see you, but\l"
    .string "this is private property, so\l"
    .string "I must ask you to leave.$"

Route2_EventScript_ChanseyGroveMan_WelcomeIn_Text::
    .string "Ah, the Kanto Champion! It's\n"
    .string "a pleasure to see you, but\l"
    .string "this is private prop-\p"
    .string "………………………\p"
    .string "Is that a Pokédex entry for\n"
    .string "Chansey…?\p"
    .string "I'm a fellow Chansey lover!\n"
    .string "You're welcome any time!$"
