---
name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  checkout:
    name: "Checkout"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            changelog
            build
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          files: |
            changelog/*
            build/cfr.bps
